os: osx
env:
  matrix:
  - CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
  global:
  # AWS S3 creds
  # access key
  - secure: "MfhOg+84yb4ZHB2tM8PIPFQX2Y+WLN0I0iiAgyLC4KaHPUoNOyloe9yk6OjV7Lj7SZWqTlQUsqHa8S9mOUswGIody1Ydglo4RvyGOKCd8I6b2ri/jE8qHVuD9sO+sNlIxq4YqqG/qReTsbSs2YEgLneZUCYLCk/fihl8L6eVuSc="
  # secret
  - secure: "JRQVU2zgC3hY6CEY+Crmh/upp93En0BzKaLcsuBT538johNlK7m5hn3m2UOw63seLvBvVaKKWUDj9N986a3DwcXxWPMyF/9ctXgNWy39WzaVWxrbVR5nQB1fdiRp5YEgkoVN+gEm3OVF7sV5AGzh5/8CvEdRCoTLIGgMGHxW9mc="
language: cpp
before_install: "./CI/install-dependencies-osx.sh"
before_script: "./CI/before-script-osx.sh"
script: cd ./build && make -j4 && cd -
before_deploy: "./CI/before-deploy-osx.sh"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true
  local_dir: nightly
  bucket: obs-nightly
  region: us-west-2
  acl: public_read
  on:
    repo: jp9000/obs-studio

# The channel name "azubu.il.us.quakenet.org#obs-dev" is encrypted against jp9000/obs-studio to prevent IRC spam of forks
notifications:
  irc:
    skip_join: true
    template:
      - "%{message} %{build_url}"
    channels:
      - secure: k9j7+ogVODMlveZdd5pP73AVLCFl1VbzVaVon0ECn3EQcxnLSpiZbc6l+PnIUKgee5pRKtUB4breufgmr4puq3s69YeQiOVKk5gx2yJGZ5jGacbSne0xTspzPxapiEbVUkcJ2L7gKntDG4+SUiW67dtt4G26O7zsErDF/lY/woQ=
